### ISSUE TITLE
Widget: language bug

### ISSUE THREAD

**Issue by paucazou** [paucazou/theochrone#22]
When the widget is loaded in english, the feasts of today are in french. But if you navigate, it switch to english, and even the feasts of the day are now in english.
Probably due to a bad request from the main page.

**Comment by paucazou** [comment]
However, if the widget is called by itself, i.e. not in another website, it is not in french, but directly in english.

**Comment by paucazou** [comment]
@BenoitHaraldsson Can you give us a little bit of help ? Just
* open a webbrowser
* set the language to any language except french
* open a blog hosting the widget, for instance tradinews.blogspot.com
* check wether the widget is in english or french (it is in the top right corner on Tradinews)
* maybe navigate between the days to see the result
* leave a comment here.
That would be great. Thanks in advance!

**Comment by BenoitEirik** [comment]
Actually the widget doesn't appear on website: tradinews.blogpost.fr
However my language browser is english.

**Comment by paucazou** [comment]
Thanks for this answer, it is very useful.
So you don't see the widget at all ? Do you see some kind of white square instead or absolutely nothing ?
Which browser do you use ? Is javascript enabled ?
Every browser I use makes appear the widget so I can't reproduce the bug.
Thanks again.

**Comment by paucazou** [comment]
Maybe you tried to see the widget in a smartphone ? If it's that, there's no problem actually: blogspot discards the side bars on mobile. So the widget only appears on desktop/laptop.

**Comment by paucazou** [comment]
I finally found the problem and probably found also a fix. It was due to the cache system of Cloudflare.
The fix consists in the detection of the language by JS inside the browser itself. No need to say this bug only appears because we lack of money.

**Comment by BenoitEirik** [comment]
Okay. Indeed I'm on mobile phone actually and my browser is currently with
JavaScript enable and desktop environment. Personally I don't know how is
the interface of your widget but I don't see absolutely nothing of this on
tradinews. Sorry for my bad english.

Le dimanche 13 mai 2018, Philippe Aucazou <notifications@github.com> a
écrit :
> I finally found the problem and probably found also a fix. It was due to
the cache system of Cloudflare.
> The fix consists in the detection of the language by JS inside the
browser itself. No need to say this bug only appears because we lack of
money.

**Comment by paucazou** [comment]
Here is a screenshot of the widget on Tradinews (in french). It's weird that you see nothing. Which browser do you currently use ? Is it on iOS or Android ?
Thanks again for your help. We need more feedback like yours. Don't worry about english, as mine is not really good: everybody speaks this kind of globish here.
Changing the subject, I saw you forked Theochrone. The structure of the program is not really clear - actually it is more or less a big mess. If you need some help to understand how it works (and maybe propose any fix or new feature ? You would be welcome !) feel free to ask.
![spectacle t31742](https://user-images.githubusercontent.com/25264379/39968407-a5fc924a-56cc-11e8-9f4e-c1de5a6177b9.png)

**Comment by BenoitEirik** [comment]
I use actually UC Browser on Android phone. From your screenshot, I do not
see anything like it. I'm going to try on other browser as Opera or Firefox
on my Android and I will say if there is a bug to confirm the "global bug"
due to the different web engines on Android.
(Personaly I'm present just the weekend for your help)

Le dimanche 13 mai 2018, Philippe Aucazou <notifications@github.com> a
écrit :
> Here is a screenshot of the widget on Tradinews (in french). It's weird
that you see nothing. Which browser do you currently use ? Is it on iOS or
Android ?
> Thanks again for your help. We need more feedback like yours. Don't worry
about english, as mine is not really good: everybody speaks this kind of
globish here.
> Changing the subject, I saw you forked Theochrone. The structure of the
program is not really clear - actually it is more or less a big mess. If
you need some help to understand how it works (and maybe propose any fix or
new feature ? You would be welcome !) feel free to ask.
> <
https://ci6.googleusercontent.com/proxy/NG9ps5wmfL3bbaNRz0FWqer8L_62lgTclSmzJa6TUHC0nPdsNJMkc_Whgf7GWJZRdsQoG8kQkWDuNRuGqoIrOZqtf2aNwFZlQtvQnVyJgZDNhw6XYaGg9JVjEplisknN7B6jNi4sEm7GGDhUfWkZ3Ps9arCP3V8ramw=s0-d-e1-ft#https://user-images.githubusercontent.com/25264379/39968407-a5fc924a-56cc-11e8-9f4e-c1de5a6177b9.png
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/m5rz9UT4D7NlB4i80MoX_KnahA6WE0y3t6wLUg3syGcsFlMmkX34-QTX9X3ygMLUfos0WjdxUFf_qIRdafqbvR_UXg_Ea1qACR-ICuDmDGtEIN05_W46fLUtlOypVZUf94-XEVq1I6uipYQFSGkNG1POqvOXVw=s0-d-e1-ft#https://github.com/notifications/beacon/AfySGgDNeDnai8XYqUPCZ-F2C_nZG8OFks5tyEjLgaJpZM4T7_Eh.gif
>

**Comment by paucazou** [comment]
Thanks for these infos. I download UC Browser (didn't know it, there's so many browsers...) and try to replicate the bug. Also, I have edited your previous messages, as I think you don't want your real name revealed to the world ;-)

**Comment by paucazou** [comment]
I can't replicate the bug. Actually, I must say that the bug seems to be gone, since I see the widget in english in UC Browser. @BenoitHaraldsson can you try to open this page: 
http://tradinews.blogspot.fr/?m=0
m=0 tells to the website to load the desktop version.

**Comment by paucazou** [comment]
Finally I did it. It seems to be the desktop mode of UC Browser which causes that problem. The mobile version with m=0 works. I close this an open a new issue. @BenoitHaraldsson Are there dev tools on UC Browser ? It would be hard to fix the bug if they are not.
Thanks again for your help, really appreciate it. Have a nice week !

**Comment by BenoitEirik** [comment]
Okay for the issue. You're welcome for the help.

Envoyé avec AquaMail pour Android
https://www.mobisystems.com/aqua-mail
